version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcs-lua-analyzer-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Update this to point to your existing database
      - DATABASE_URL=postgresql://dcs_user:secure_password@host.docker.internal:5433/vectordb
      - PORT=8000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_EMBEDDING_MODEL=nomic-embed-text
      - OLLAMA_LLM_MODEL=codegemma
      - USE_OLLAMA=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - open-webui-network  # Shared network with Open WebUI

networks:
  open-webui-network:
    external: true  # Connect to existing Open WebUI network
    name: open-webui_default  # Adjust this to match your Open WebUI network name