version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcs-lua-analyzer-api
    restart: unless-stopped
    network_mode: bridge  # Use bridge network mode
    ports:
      - "8000:8000"
    environment:
      # Database connection - this points to the PostgreSQL database on the host
      - DATABASE_URL=postgresql://dcs_user:secure_password@host.docker.internal:5433/vectordb
      - PORT=8000
      # Ollama connection - using localhost for direct connection to host machine
      - OLLAMA_BASE_URL=http://localhost:11434
      - OLLAMA_EMBEDDING_MODEL=nomic-embed-text
      - OLLAMA_LLM_MODEL=codegemma
      - USE_OLLAMA=true
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Makes host.docker.internal work on Linux